version : '3.8'
services:
  # AASさんから、とりあえず不要だと聞いたから一旦対応しない
  # preparation-roof-surface:
  #   image: bldg-lod2-tool-preparation-roof-surface
  #   build:
  #     context: ./tools/SuperResolution/RoofSurface
  #   tty: true
  #   stdin_open: true
  #   command: /bin/bash -c "sleep 1000000"
  #   volumes:
  #     - ~/lod2_data/kawazaki:/app/input
  #     - ~/lod2_data/kawazaki/output:/app/output
  #   environment:
  #     PARAM_JSON: '{
  #       "InputDir": "/app/input/result",
  #       "OutputDir": "/app/output/result",
  #       "GSD": "0.25",
  #       "Device": "cuda",
  #       "OutputLogDir": "/app/output/log",
  #       "DebugLogOutput": "false"
  #     }'
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]
  3d-model:
    image: bldg-lod2-tool-3d-model
    build:
      context: .
    tty: true
    stdin_open: true
    command: /bin/bash -c "sleep 1000000"
    volumes:
      - ~/lod2_data/kawazaki:/app/input
      - ~/lod2_data/kawazaki/output:/app/output
    environment:
      PARAM_JSON: '{
        "TextureFolderPath": "/app/input/01_原画像",
        "ExternalCalibElementPath": "/app/input/02_外部標定要素/ExCalib.txt",
        "CameraInfoPath": "/app/input/03_内部標定要素/CamInfo.txt",
        "DsmFolderPath": "/app/input/04_DSM_RGB",
        "CityGMLFolderPath": "/app/input/08_CityGML",
        "LasCoordinateSystem": 9,
        "LasSwapXY": false,
        "RotateMatrixMode": 0,
        "OutputFolderPath": "/app/output",
        "OutputOBJ": true,
        "OutputTexture": true,
        "OutputLogFolderPath": "/app/output",
        "DebugLogOutput": true,
        "PhaseConsistency": {
          "DeleteErrorObject": true,
          "NonPlaneThickness": 0.05,
          "NonPlaneAngle": 15
        },
        "DebugMode": false,
        "TargetCoordAreas": null,
        "TargetBuildingIds": null,
        "TextureOutputWidthMax": 2048,
        "TextureOutputHeightMax": 2048
      }'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  texture-wall-surface:
    image: bldg-lod2-tool-texture-wall-surface
    build:
      context: ./tools/SuperResolution/WallSurface
    tty: true
    stdin_open: true
    command: /bin/bash -c "sleep 1000000"
    volumes:
      - ~/lod2_data/kawazaki/output/output_latest_bldb-lod2-tool:/app/input
      - ~/lod2_data/kawazaki/output:/app/output
    environment:
      PARAM_JSON: '{
        "InputDir": "/app/input",
        "OutputDir": "/app/output/output_latest_wall_surface",
        "GSD": "0.25",
        "Device": "cuda",
        "OutputLogDir": "/app/output/log",
        "DebugLogOutput": "false"
      }'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  texture-deblurgan:
    image: bldg-lod2-tool-texture-deblurgan
    build:
      context: ./tools/DeblurGANv2
    tty: true
    stdin_open: true
    command: /bin/bash -c "sleep 1000000"
    volumes:
      - ~/lod2_data/kawazaki/output/output_latest_wall_surface:/app/input
      - ~/lod2_data/kawazaki/output/:/app/output
    environment:
      InputGMLFolderPath: '/app/input'
      OutputGMLFolderPath: '/app/output/output_latest_deblurgan'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  texture-unsharp-mask:
    image: bldg-lod2-tool-texture-unsharp-mask
    build:
      context: ./tools/UnsharpMask
    tty: true
    stdin_open: true
    command: /bin/bash -c "sleep 1000000"
    volumes:
      - ~/lod2_data/kawazaki/output/output_latest_deblurgan:/app/input
      - ~/lod2_data/kawazaki/output/:/app/output
    environment:
      InputGMLFolderPath: '/app/input'
      OutputGMLFolderPath: '/app/output/output_latest_unsharp_mask'
  texture-esrgan:
    image: bldg-lod2-tool-texture-esrgan
    build:
      context: ./tools/Real-ESRGAN
    tty: true
    stdin_open: true
    command: /bin/bash -c "sleep 1000000"
    volumes:
      - ~/lod2_data/kawazaki/output/output_latest_unsharp_mask:/app/input
      - ~/lod2_data/kawazaki/output/:/app/output
    environment:
      InputGMLFolderPath: '/app/input'
      OutputGMLFolderPath: '/app/output/output_latest_esrgan'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  texture-atlas-prot:
    image: bldg-lod2-tool-texture-atlas-prot
    build:
      context: ./tools/Atlas_Prot
    tty: true
    stdin_open: true
    command: /bin/bash -c "sleep 1000000"
    volumes:
      - ~/lod2_data/kawazaki/output/output_latest_esrgan:/app/input
      - ~/lod2_data/kawazaki/output:/app/output
    environment:
      PARAM_JSON: '{
        "FilePath": {
          "InputGMLFolderPath": "/app/input",
          "OutputGMLFolderPath": "/app/output/output_latest_atlas_prot"
        },
        "OutputWidth": 2048,
        "OutputHeight": 2048,
        "BackGroundColor": 255,
        "Extentpixel": 1
      }'
